Repository arcalos-environments/environment-lordlemon-dev, pull requests merged in 2019-10, with the labels that each got.

#2 chore: add the tenant service and arcalosui
  env/arcalosui/templates/ingress.yaml
  env/arcalosui/values.yaml
  env/jx-tenant-service/templates/ingress.yaml
  env/jx-tenant-service/values.yaml
  env/requirements.yaml
  env/values.tmpl.yaml
Labels: approved, ok-to-test, size/M

#10 chore: restrict ingress to tenant service
  env/templates/jx-tenant-service-ingress.yaml
Labels: size/XS

#16 fix: updated jx-tenant-service to use jxaas.dev
  env/jx-tenant-service/values.yaml
Labels: approved, size/XS

#31 chore: fix syntax
  env/arcalosui/values.tmpl.yaml
Labels: size/XS

#35 Chore: template domainIssuerUrl
  env/values.tmpl.yaml
Labels: size/XS

#40 fix: oops, wrong name for ingress
  env/templates/700-arcalosui-ing.yaml
  env/templates/700-jx-tenant-service-ing.yaml
Labels: approved, lgtm, size/XS

#41 fix: more bad copy-and-paste
  env/arcalosui/values.tmpl.yaml
  env/templates/700-arcalosui-ing.yaml
  env/templates/700-jx-tenant-service-ing.yaml
Labels: size/XS

#54 fix: updated jx-tenant-service to use jxaas.page domain
  env/parameters.yaml
Labels: size/XS

#57 chore: update domain of lordlemon to use jxaas.live
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#58 chore: actually update environment to use jxaas.live
  jx-requirements.yml
Labels: approved, size/XS

#59 chore: updated tenant-service issuing domain to jxaas.live
  env/parameters.yaml
  jx-requirements.yml
Labels: approved, size/XS

#60 chore: support dashboard.jxaas.live and dex-jx.jxaas.live using cname
  env/arcalosui/values.tmpl.yaml
  env/jx-app-sso/values.tmpl.yaml
  env/templates/700-arcalosui-ing.yaml
  env/templates/700-dex-ing.yaml
  env/values.tmpl.yaml
  jx-requirements.yml
  systems/acme/templates/cert-manager-prod-certificate.yaml
  systems/acme/templates/cert-manager-prod-issuer.yaml
  systems/acme/templates/cert-manager-staging-certificate.yaml
  systems/acme/templates/cert-manager-staging-issuer.yaml
  systems/acme/values.tmpl.yaml
Labels: approved, size/L

#61 chore: fix syntax errors
  jenkins-x.yml
  systems/acme/Makefile
  systems/acme/templates/cert-manager-prod-issuer.yaml
  systems/acme/templates/cert-manager-staging-issuer.yaml
Labels: approved, size/S

#63 Chore: fix syntax error
  env/templates/700-arcalosui-ing.yaml
  env/templates/700-dex-ing.yaml
Labels: approved, size/XS

#64 Chore: fix syntax error
  env/arcalosui/values.tmpl.yaml
  env/jx-app-sso/values.tmpl.yaml
  env/templates/700-arcalosui-ing.yaml
  env/templates/700-dex-ing.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#65 feat: promote latest tenant service and arcalos ui
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  env/jx-tenant-service/values.tmpl.yaml
  env/requirements.yaml
  env/templates/700-jx-tenant-service-ing.yaml
  env/values.tmpl.yaml
  jenkins-x.yml
  jx-requirements.yml
Labels: approved, size/M

#67 feat: upgrade tenant service and create tenants in dedicated GCP folder
  env/jx-tenant-service/values.tmpl.yaml
  env/requirements.yaml
Labels: size/XS
